name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_octicon: true
          config_timezone: Asia/Kolkata
          config_twemoji: true
          
          # Languages plugin
          plugin_languages: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          
          # Commit to repository
          filename: github-metrics.svg
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_branch: main
          committer_message: "📈 Update GitHub metrics [skip ci]"
